# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_create_environment:
      - curl -sSL https://install.python-poetry.org | python3 -
    pre_install:
      - /home/docs/.local/bin/poetry export --only=docs -o docs-requirements.txt

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
