"""initial schema

Revision ID: 4d14d2e9a25e
Revises:
Create Date: 2026-08-10 21:49:03.560598+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

import aimbat._types

# revision identifiers, used by Alembic.
revision: str = "4d14d2e9a25e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aimbatevent",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "time", aimbat._types.SAPandasTimestamp(timezone=True), nullable=False
        ),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("depth", sa.Float(), nullable=True),
        sa.Column(
            "last_modified",
            aimbat._types.SAPandasTimestamp(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("time"),
    )
    op.create_table(
        "aimbatstation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("network", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("elevation", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbateventparameters",
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("ramp_width", sa.Float(), nullable=False),
        sa.Column("window_pre", aimbat._types.SAPandasTimedelta(), nullable=False),
        sa.Column("window_post", aimbat._types.SAPandasTimedelta(), nullable=False),
        sa.Column("bandpass_apply", sa.Boolean(), nullable=False),
        sa.Column("bandpass_fmin", sa.Float(), nullable=False),
        sa.Column("bandpass_fmax", sa.Float(), nullable=False),
        sa.Column("min_cc", sa.Float(), nullable=False),
        sa.Column("mccc_damp", sa.Float(), nullable=False),
        sa.Column("mccc_min_cc", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["aimbatevent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbateventquality",
        sa.Column("mccc_rmse", aimbat._types.SAPandasTimedelta(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["aimbatevent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbatseismogram",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "begin_time", aimbat._types.SAPandasTimestamp(timezone=True), nullable=False
        ),
        sa.Column("delta", aimbat._types.SAPandasTimedelta(), nullable=False),
        sa.Column("t0", aimbat._types.SAPandasTimestamp(timezone=True), nullable=False),
        sa.Column("station_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("extra", sa.PickleType(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["aimbatevent.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["station_id"], ["aimbatstation.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbatsnapshot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "time", aimbat._types.SAPandasTimestamp(timezone=True), nullable=False
        ),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parameters_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["aimbatevent.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("time"),
    )
    op.create_table(
        "aimbatdatasource",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sourcename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "datatype",
            sa.Enum("SAC", "JSON_EVENT", "JSON_STATION", name="datatype"),
            nullable=False,
        ),
        sa.Column("seismogram_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seismogram_id"], ["aimbatseismogram.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbateventparameterssnapshot",
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("ramp_width", sa.Float(), nullable=False),
        sa.Column("window_pre", aimbat._types.SAPandasTimedelta(), nullable=False),
        sa.Column("window_post", aimbat._types.SAPandasTimedelta(), nullable=False),
        sa.Column("bandpass_apply", sa.Boolean(), nullable=False),
        sa.Column("bandpass_fmin", sa.Float(), nullable=False),
        sa.Column("bandpass_fmax", sa.Float(), nullable=False),
        sa.Column("min_cc", sa.Float(), nullable=False),
        sa.Column("mccc_damp", sa.Float(), nullable=False),
        sa.Column("mccc_min_cc", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("parameters_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parameters_id"], ["aimbateventparameters.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["aimbatsnapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbateventqualitysnapshot",
        sa.Column("mccc_rmse", aimbat._types.SAPandasTimedelta(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_quality_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_quality_id"], ["aimbateventquality.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["aimbatsnapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbatnote",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("station_id", sa.Uuid(), nullable=True),
        sa.Column("seismogram_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(CASE WHEN event_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN station_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN seismogram_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN snapshot_id IS NOT NULL THEN 1 ELSE 0 END) = 1",
            name="aimbat_note_exactly_one_parent",
        ),
        sa.ForeignKeyConstraint(["event_id"], ["aimbatevent.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["seismogram_id"], ["aimbatseismogram.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["aimbatsnapshot.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["station_id"], ["aimbatstation.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbatseismogramparameters",
        sa.Column("flip", sa.Boolean(), nullable=False),
        sa.Column("select", sa.Boolean(), nullable=False),
        sa.Column("t1", aimbat._types.SAPandasTimestamp(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seismogram_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seismogram_id"], ["aimbatseismogram.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbatseismogramquality",
        sa.Column("iccs_cc", sa.Float(), nullable=True),
        sa.Column("mccc_cc_mean", sa.Float(), nullable=True),
        sa.Column("mccc_cc_std", sa.Float(), nullable=True),
        sa.Column("mccc_error", aimbat._types.SAPandasTimedelta(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seismogram_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seismogram_id"], ["aimbatseismogram.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbatseismogramparameterssnapshot",
        sa.Column("flip", sa.Boolean(), nullable=False),
        sa.Column("select", sa.Boolean(), nullable=False),
        sa.Column("t1", aimbat._types.SAPandasTimestamp(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seismogram_parameters_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seismogram_parameters_id"],
            ["aimbatseismogramparameters.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["aimbatsnapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aimbatseismogramqualitysnapshot",
        sa.Column("iccs_cc", sa.Float(), nullable=True),
        sa.Column("mccc_cc_mean", sa.Float(), nullable=True),
        sa.Column("mccc_cc_std", sa.Float(), nullable=True),
        sa.Column("mccc_error", aimbat._types.SAPandasTimedelta(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seismogram_quality_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["seismogram_quality_id"],
            ["aimbatseismogramquality.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["aimbatsnapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # The seven triggers below are not part of SQLModel's metadata (they are
    # hand-written DDL executed imperatively by
    # `core._project.create_project()`), so autogenerate cannot see or
    # produce them. Keep this block in sync with `create_project()` by hand;
    # any future trigger change needs its own manual migration.
    if op.get_bind().dialect.name == "sqlite":
        # Trigger 1: Track last modification time when event parameters change
        op.execute(
            sa.text("""
            CREATE TRIGGER IF NOT EXISTS event_modified_on_params_update
            AFTER UPDATE ON aimbateventparameters
            BEGIN
                UPDATE aimbatevent SET last_modified = strftime('%Y-%m-%d %H:%M:%f', 'now')
                WHERE id = NEW.event_id;
            END;
        """)
        )

        # Trigger 2: Track last modification time when seismogram parameters change
        op.execute(
            sa.text("""
            CREATE TRIGGER IF NOT EXISTS event_modified_on_seis_params_update
            AFTER UPDATE ON aimbatseismogramparameters
            BEGIN
                UPDATE aimbatevent
                SET last_modified = strftime('%Y-%m-%d %H:%M:%f', 'now')
                WHERE id = (
                    SELECT event_id FROM aimbatseismogram
                    WHERE id = NEW.seismogram_id
                );
            END;
        """)
        )

        # Trigger 3: Null all quality when event window/bandpass/ramp parameters change.
        # These parameters change the signal data used by both ICCS and MCCC.
        op.execute(
            sa.text("""
            CREATE TRIGGER IF NOT EXISTS null_all_quality_on_window_bandpass_change
            AFTER UPDATE ON aimbateventparameters
            WHEN (NEW.window_pre IS NOT OLD.window_pre)
              OR (NEW.window_post IS NOT OLD.window_post)
              OR (NEW.ramp_width IS NOT OLD.ramp_width)
              OR (NEW.bandpass_apply IS NOT OLD.bandpass_apply)
              OR (NEW.bandpass_fmin IS NOT OLD.bandpass_fmin)
              OR (NEW.bandpass_fmax IS NOT OLD.bandpass_fmax)
            BEGIN
                UPDATE aimbateventquality
                SET mccc_rmse = NULL
                WHERE event_id = NEW.event_id;
                UPDATE aimbatseismogramquality
                SET iccs_cc = NULL, mccc_cc_mean = NULL, mccc_cc_std = NULL, mccc_error = NULL
                WHERE seismogram_id IN (
                    SELECT id FROM aimbatseismogram WHERE event_id = NEW.event_id
                );
            END;
        """)
        )

        # Trigger 4: Null MCCC quality when MCCC-specific event parameters change.
        # These parameters affect only the MCCC inversion, not the underlying signal,
        # so iccs_cc remains valid.
        op.execute(
            sa.text("""
            CREATE TRIGGER IF NOT EXISTS null_mccc_quality_on_mccc_params_change
            AFTER UPDATE ON aimbateventparameters
            WHEN (NEW.mccc_damp IS NOT OLD.mccc_damp)
              OR (NEW.mccc_min_cc IS NOT OLD.mccc_min_cc)
            BEGIN
                UPDATE aimbateventquality
                SET mccc_rmse = NULL
                WHERE event_id = NEW.event_id;
                UPDATE aimbatseismogramquality
                SET mccc_cc_mean = NULL, mccc_cc_std = NULL, mccc_error = NULL
                WHERE seismogram_id IN (
                    SELECT id FROM aimbatseismogram WHERE event_id = NEW.event_id
                );
            END;
        """)
        )

        # Trigger 5a: Null quality when flip changes on a seismogram.
        # Flipping a trace only affects the ICCS stack if the seismogram is selected.
        # MCCC stats are invalidated if the seismogram was included in the last MCCC
        # run, which is inferred from the presence of live mccc_cc_mean stats —
        # not from select, because MCCC may have been run with --all.
        # The event-level UPDATE is ordered before the per-seismogram UPDATE so that
        # the EXISTS check sees the original (non-nulled) stats in both statements.
        op.execute(
            sa.text("""
            CREATE TRIGGER IF NOT EXISTS null_quality_on_seis_flip_change
            AFTER UPDATE ON aimbatseismogramparameters
            WHEN NEW.flip IS NOT OLD.flip
            BEGIN
                -- Null iccs_cc for all event seismograms if selected (stack changed),
                -- or just locally if deselected (the flipped seismogram's own CC is stale
                -- even though the stack is unchanged).
                UPDATE aimbatseismogramquality
                SET iccs_cc = NULL
                WHERE (
                    NEW."select" = TRUE
                    AND seismogram_id IN (
                        SELECT id FROM aimbatseismogram WHERE event_id = (
                            SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                        )
                    )
                ) OR (
                    NEW."select" IS NOT TRUE
                    AND seismogram_id = NEW.seismogram_id
                );

                -- Null event-level RMSE if this seismogram was in the last MCCC run
                UPDATE aimbateventquality
                SET mccc_rmse = NULL
                WHERE EXISTS (
                    SELECT 1 FROM aimbatseismogramquality
                    WHERE seismogram_id = NEW.seismogram_id
                      AND mccc_cc_mean IS NOT NULL
                )
                  AND event_id = (
                    SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                );

                -- Null per-seismogram MCCC stats for the whole event if this seismogram
                -- was in the last MCCC run (checked before these stats are nulled above)
                UPDATE aimbatseismogramquality
                SET mccc_cc_mean = NULL, mccc_cc_std = NULL, mccc_error = NULL
                WHERE EXISTS (
                    SELECT 1 FROM aimbatseismogramquality
                    WHERE seismogram_id = NEW.seismogram_id
                      AND mccc_cc_mean IS NOT NULL
                )
                  AND seismogram_id IN (
                    SELECT id FROM aimbatseismogram WHERE event_id = (
                        SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                    )
                );
            END;
        """)
        )

        # Trigger 5b: Null quality when t1 changes on a seismogram.
        # ICCS: if selected, the stack is affected so iccs_cc is stale for all;
        # if deselected, only this seismogram's own iccs_cc is stale.
        # MCCC: invalidated whenever the seismogram was in the last MCCC run,
        # inferred from live mccc_cc_mean — not select — because MCCC may have
        # been run with --all, meaning a deselected seismogram could still be included.
        op.execute(
            sa.text("""
            CREATE TRIGGER IF NOT EXISTS null_quality_on_seis_t1_change
            AFTER UPDATE ON aimbatseismogramparameters
            WHEN NEW.t1 IS NOT OLD.t1
            BEGIN
                -- Null iccs_cc for all event seismograms if selected (stack changed),
                -- otherwise only null locally.
                UPDATE aimbatseismogramquality
                SET iccs_cc = NULL
                WHERE (
                    NEW."select" = TRUE
                    AND seismogram_id IN (
                        SELECT id FROM aimbatseismogram WHERE event_id = (
                            SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                        )
                    )
                ) OR (
                    NEW."select" IS NOT TRUE
                    AND seismogram_id = NEW.seismogram_id
                );

                -- Null event-level RMSE if this seismogram was in the last MCCC run
                UPDATE aimbateventquality
                SET mccc_rmse = NULL
                WHERE EXISTS (
                    SELECT 1 FROM aimbatseismogramquality
                    WHERE seismogram_id = NEW.seismogram_id
                      AND mccc_cc_mean IS NOT NULL
                )
                  AND event_id = (
                    SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                );

                -- Null per-seismogram MCCC stats for the whole event if this seismogram
                -- was in the last MCCC run
                UPDATE aimbatseismogramquality
                SET mccc_cc_mean = NULL, mccc_cc_std = NULL, mccc_error = NULL
                WHERE EXISTS (
                    SELECT 1 FROM aimbatseismogramquality
                    WHERE seismogram_id = NEW.seismogram_id
                      AND mccc_cc_mean IS NOT NULL
                )
                  AND seismogram_id IN (
                    SELECT id FROM aimbatseismogram WHERE event_id = (
                        SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                    )
                );
            END;
        """)
        )

        # Trigger 5c: Null quality when select changes on a seismogram.
        # ICCS stack composition changes in both directions (select → deselect and
        # vice versa), so iccs_cc is always invalidated for the whole event.
        # MCCC stats are only invalidated if the seismogram was in the last MCCC run,
        # inferred from live mccc_cc_mean — if MCCC was run with --all, changing
        # select does not change the MCCC set, so live stats remain valid.
        op.execute(
            sa.text("""
            CREATE TRIGGER IF NOT EXISTS null_quality_on_seis_select_change
            AFTER UPDATE ON aimbatseismogramparameters
            WHEN NEW."select" IS NOT OLD."select"
            BEGIN
                -- Always null iccs_cc for the whole event (stack composition changed)
                UPDATE aimbatseismogramquality
                SET iccs_cc = NULL
                WHERE seismogram_id IN (
                    SELECT id FROM aimbatseismogram WHERE event_id = (
                        SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                    )
                );

                -- Null event-level RMSE if this seismogram was in the last MCCC run
                UPDATE aimbateventquality
                SET mccc_rmse = NULL
                WHERE EXISTS (
                    SELECT 1 FROM aimbatseismogramquality
                    WHERE seismogram_id = NEW.seismogram_id
                      AND mccc_cc_mean IS NOT NULL
                )
                  AND event_id = (
                    SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                );

                -- Null per-seismogram MCCC stats for the whole event if this seismogram
                -- was in the last MCCC run
                UPDATE aimbatseismogramquality
                SET mccc_cc_mean = NULL, mccc_cc_std = NULL, mccc_error = NULL
                WHERE EXISTS (
                    SELECT 1 FROM aimbatseismogramquality
                    WHERE seismogram_id = NEW.seismogram_id
                      AND mccc_cc_mean IS NOT NULL
                )
                  AND seismogram_id IN (
                    SELECT id FROM aimbatseismogram WHERE event_id = (
                        SELECT event_id FROM aimbatseismogram WHERE id = NEW.seismogram_id
                    )
                );
            END;
        """)
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        op.execute(sa.text("DROP TRIGGER IF EXISTS null_quality_on_seis_select_change"))
        op.execute(sa.text("DROP TRIGGER IF EXISTS null_quality_on_seis_t1_change"))
        op.execute(sa.text("DROP TRIGGER IF EXISTS null_quality_on_seis_flip_change"))
        op.execute(
            sa.text("DROP TRIGGER IF EXISTS null_mccc_quality_on_mccc_params_change")
        )
        op.execute(
            sa.text("DROP TRIGGER IF EXISTS null_all_quality_on_window_bandpass_change")
        )
        op.execute(
            sa.text("DROP TRIGGER IF EXISTS event_modified_on_seis_params_update")
        )
        op.execute(sa.text("DROP TRIGGER IF EXISTS event_modified_on_params_update"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("aimbatseismogramqualitysnapshot")
    op.drop_table("aimbatseismogramparameterssnapshot")
    op.drop_table("aimbatseismogramquality")
    op.drop_table("aimbatseismogramparameters")
    op.drop_table("aimbatnote")
    op.drop_table("aimbateventqualitysnapshot")
    op.drop_table("aimbateventparameterssnapshot")
    op.drop_table("aimbatdatasource")
    op.drop_table("aimbatsnapshot")
    op.drop_table("aimbatseismogram")
    op.drop_table("aimbateventquality")
    op.drop_table("aimbateventparameters")
    op.drop_table("aimbatstation")
    op.drop_table("aimbatevent")
    # ### end Alembic commands ###
