"""add corners to event parameters

Revision ID: ffa5c8fcbe9b
Revises: 64c531b83e89
Create Date: 2026-08-16 11:43:01.732968+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffa5c8fcbe9b"
down_revision: str | None = "64c531b83e89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# SQLite's batch mode recreates `aimbateventparameters` from scratch to add the
# `corners` column, which silently drops every trigger defined on that table -
# they're raw SQL outside SQLAlchemy's metadata, so Alembic doesn't know to
# recreate them. All three must be dropped and recreated here, not just the one
# whose WHEN clause actually changed. See core/_project.py::create_project() -
# these bodies must stay byte-for-byte (modulo whitespace) in sync with there,
# checked by tests/integration/core/test_migrations.py::test_same_triggers.

_EVENT_MODIFIED_ON_PARAMS_UPDATE = """
    CREATE TRIGGER IF NOT EXISTS event_modified_on_params_update
    AFTER UPDATE ON aimbateventparameters
    BEGIN
        UPDATE aimbatevent SET last_modified = strftime('%Y-%m-%d %H:%M:%f', 'now')
        WHERE id = NEW.event_id;
    END;
"""

_NULL_MCCC_QUALITY_ON_MCCC_PARAMS_CHANGE = """
    CREATE TRIGGER IF NOT EXISTS null_mccc_quality_on_mccc_params_change
    AFTER UPDATE ON aimbateventparameters
    WHEN (NEW.mccc_damp IS NOT OLD.mccc_damp)
      OR (NEW.mccc_min_cc IS NOT OLD.mccc_min_cc)
    BEGIN
        UPDATE aimbateventquality
        SET mccc_rmse = NULL
        WHERE event_id = NEW.event_id;
        UPDATE aimbatseismogramquality
        SET mccc_cc_mean = NULL, mccc_cc_std = NULL, mccc_error = NULL
        WHERE seismogram_id IN (
            SELECT id FROM aimbatseismogram WHERE event_id = NEW.event_id
        );
    END;
"""

_NULL_ALL_QUALITY_ON_WINDOW_BANDPASS_CHANGE_NEW = """
    CREATE TRIGGER IF NOT EXISTS null_all_quality_on_window_bandpass_change
    AFTER UPDATE ON aimbateventparameters
    WHEN (NEW.window_pre IS NOT OLD.window_pre)
      OR (NEW.window_post IS NOT OLD.window_post)
      OR (NEW.ramp_width IS NOT OLD.ramp_width)
      OR (NEW.bandpass_apply IS NOT OLD.bandpass_apply)
      OR (NEW.bandpass_fmin IS NOT OLD.bandpass_fmin)
      OR (NEW.bandpass_fmax IS NOT OLD.bandpass_fmax)
      OR (NEW.corners IS NOT OLD.corners)
    BEGIN
        UPDATE aimbateventquality
        SET mccc_rmse = NULL
        WHERE event_id = NEW.event_id;
        UPDATE aimbatseismogramquality
        SET iccs_cc = NULL, mccc_cc_mean = NULL, mccc_cc_std = NULL, mccc_error = NULL
        WHERE seismogram_id IN (
            SELECT id FROM aimbatseismogram WHERE event_id = NEW.event_id
        );
    END;
"""

_NULL_ALL_QUALITY_ON_WINDOW_BANDPASS_CHANGE_OLD = """
    CREATE TRIGGER IF NOT EXISTS null_all_quality_on_window_bandpass_change
    AFTER UPDATE ON aimbateventparameters
    WHEN (NEW.window_pre IS NOT OLD.window_pre)
      OR (NEW.window_post IS NOT OLD.window_post)
      OR (NEW.ramp_width IS NOT OLD.ramp_width)
      OR (NEW.bandpass_apply IS NOT OLD.bandpass_apply)
      OR (NEW.bandpass_fmin IS NOT OLD.bandpass_fmin)
      OR (NEW.bandpass_fmax IS NOT OLD.bandpass_fmax)
    BEGIN
        UPDATE aimbateventquality
        SET mccc_rmse = NULL
        WHERE event_id = NEW.event_id;
        UPDATE aimbatseismogramquality
        SET iccs_cc = NULL, mccc_cc_mean = NULL, mccc_cc_std = NULL, mccc_error = NULL
        WHERE seismogram_id IN (
            SELECT id FROM aimbatseismogram WHERE event_id = NEW.event_id
        );
    END;
"""

_EVENT_PARAMS_TRIGGER_NAMES = (
    "event_modified_on_params_update",
    "null_all_quality_on_window_bandpass_change",
    "null_mccc_quality_on_mccc_params_change",
)


def upgrade() -> None:
    for name in _EVENT_PARAMS_TRIGGER_NAMES:
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS {name}"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aimbateventparameters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "corners", sa.Integer(), nullable=False, server_default=sa.text("2")
            )
        )

    with op.batch_alter_table("aimbateventparameterssnapshot", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "corners", sa.Integer(), nullable=False, server_default=sa.text("2")
            )
        )

    # ### end Alembic commands ###

    op.execute(sa.text(_EVENT_MODIFIED_ON_PARAMS_UPDATE))
    op.execute(sa.text(_NULL_ALL_QUALITY_ON_WINDOW_BANDPASS_CHANGE_NEW))
    op.execute(sa.text(_NULL_MCCC_QUALITY_ON_MCCC_PARAMS_CHANGE))


def downgrade() -> None:
    for name in _EVENT_PARAMS_TRIGGER_NAMES:
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS {name}"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aimbateventparameterssnapshot", schema=None) as batch_op:
        batch_op.drop_column("corners")

    with op.batch_alter_table("aimbateventparameters", schema=None) as batch_op:
        batch_op.drop_column("corners")

    # ### end Alembic commands ###

    op.execute(sa.text(_EVENT_MODIFIED_ON_PARAMS_UPDATE))
    op.execute(sa.text(_NULL_ALL_QUALITY_ON_WINDOW_BANDPASS_CHANGE_OLD))
    op.execute(sa.text(_NULL_MCCC_QUALITY_ON_MCCC_PARAMS_CHANGE))
