"""add automatic column to snapshot

Revision ID: 64c531b83e89
Revises: 4d14d2e9a25e
Create Date: 2026-08-15 20:57:50.282847+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64c531b83e89"
down_revision: str | None = "4d14d2e9a25e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aimbatsnapshot", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "automatic",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aimbatsnapshot", schema=None) as batch_op:
        batch_op.drop_column("automatic")

    # ### end Alembic commands ###
