name: build

on:
  workflow_run:
    workflows:
      - "unit tests"
    branches:
      - master
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: pysmo/.github/.github/workflows/build.yml@main
