name: Documentation

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: pysmo/.github/.github/workflows/docs.yml@main
