# .github/workflows/pull-request-links.yaml

name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened
    # Execute this action only on PRs that touch
    # documentation files.
    # paths:
    #   - "docs/**"

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    uses: pysmo/.github/.github/workflows/pull-request-links.yml@main
    with:
      project-slug: "aimbat"
